function mouseIP = processPupil (mouse)
%{ 
    The purpose of this function is to interpolate and low pass filter 
    raw pupil data read by readPupil within buildMousePupil 

    It will replace mouse.pupil with the interpolated data and create 
    a new field in the struct called mouse.pupilRaw that contains
    the original data. This will keep the original raw data accessible
    while allowing plotting functions to work without directing them
    away from raw and to interpolated and LPF data. 

    Input:
        mouse       |   Structure generated by buildMousePupil
        
    Output:
        mouseIP     |   The same strucutre but with above noted additions
                        and modifications 

%}

    %% Extract raw pupil radius data from mouse
    
    pupilsR = mouse.pupils.major_r
    mouseIP = mouse
    mouseIP.pupils.major_r_raw = pupilsR   % save raw data from before interpolation etc.
    
    %% Iterate through pupil videos and process radii recordings
    A = length(pupilsR)
    for kk = 1:A
        %% Convert cell array into vector 
            % Convert pupilsR{kk} into vector for interpolation and low pass
            cur = pupilsR{kk}
            curEmptyIndex = cellfun('isempty', cur)
            cur(curEmptyIndex)={NaN}
            curVec = cell2mat(cur)        
            
        
        %% Interpolate NaNs
            xdata=(1:length(curVec))'
            curVec = interp1(...
                                    xdata(~isnan(curVec)), ...
                                    curVec(~isnan(curVec)), ...
                                    xdata)
            

        
        
        %% Low Pass filter to remove noise
            % Low pass curVec at 100 Hz noting that it is recorded at 30 Hz
            curVec =  lowpass(curVec, 15, 30)


        %% Return processed vector 
        pupilsR{kk} = curVec
    
        
    %% Pass processed pupil data back to mouse
    mouseIP.pupils.major_r = pupilsR
    end 
    