function fig = plotFOV(vector_FOV, tRes)
    %{
        Introduction
            Plot percent field of view active per second

        Inputs:
            vec_FOV     |   Vector of % Field of View Active as generated by detectFOV()

            tRes        |   Temporal resolution of video, i.e. seconds per frame
            

        Outputs:
            fig         |   Return plot handle for further manipulation
    
    %}
    
    % Pull basic data
    epercEvts = vector_FOV;

    % Set up colors and color spaceing from colorbrewer
    N=9;
    C = linspecer(N,'qualitative');

    % Create figure
    fig = figure();

    % Test line below
    %line(1:length(epercEvts), repmat(thr,length(epercEvts)),'LineStyle',':','Color','r','MarkerSize',10,'LineWidth',2); hold on;
    
    % Plot
    plot(epercEvts,'Color','k','LineWidth',3); 
    hold on;
    xlabel('time (sec)')
    ylabel('% FOV')
    axis([0 length(epercEvts) 0 (max(epercEvts)+5)])
    set(gca,'fontsize',18)
    box off

end